spring:
  profiles:
    active: 8096
  application:
    name: orderservice
---
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
---
spring:
  cloud:
    nacos:
      server-addr: 192.168.70.130:8848  #注册中心的地址
      discovery:
        cluster-name: AHGYDX  #集群名字
---
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
---

