server:
  port: 8095
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.70.130:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true
    username: myuser
    password: myuser
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: userservices
---
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo
---
#driver-class-name: oracle.jdbc.OracleDriver
#url: jdbc:oracle:thin:@192.168.70.130:1521:helowin
#username: ${profile.name}
#password: ${profile.password}

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
---
spring:
  cloud:
    nacos:
      server-addr: 192.168.70.130:8848  #注册中心的地址
      discovery:
        cluster-name: AHGYDX  #集群名字
---
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
---
spring:
  rabbitmq:
    host: 192.168.70.130 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: develop
    password: develop
    virtual-host: /
