



POST http://localhost:60006/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"123","password":"123","authType":"password"}
###
POST http://localhost:63070/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=5ynqX6&redirect_uri=http://www.51xuecheng.cn
###
POST http://localhost:63070/auth/oauth/authorize?client_id=XcWebApp&response_type=code&scope=all&redirect_uri=http://www.51xuecheng.cn
###
POST http://localhost:63070/auth/oauth/check_token?token=


###