server:
  port: 10010
---
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        cluster-name: AHGYDX  #集群名字

---
spring:
  cloud:
    nacos:
      server-addr: 192.168.70.130:8848 # nacos地址
    gateway:
      routes:
        - id: userservice      # 路由标示，必须唯一
          uri: lb://userserver # 路由的目标地址
          predicates:           # 路由断言，判断请求是否符合规则
            - Path=/User/**     # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: orderservice
          uri: lb://orderserver
          predicates:
            - Path=/Order/**
---
