
#服务端口号
server:
  port: 8090
---
#数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.70.130:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true
    username: myuser
    password: myuser
    type: com.alibaba.druid.pool.DruidDataSource
---
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo
---
#消息队列
spring:
  rabbitmq:
    host: 192.168.70.130 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: develop
    password: develop
    virtual-host: /
---
