spring:
  profiles:
    active: ${profile.active}
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.70.130:1521:helowin
    username: ${profile.name}
    password: ${profile.password}
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: userserver
---
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
---
spring:
  cloud:
    nacos:
      server-addr: 192.168.70.130:8848  #注册中心的地址
      discovery:
        cluster-name: AHGYDX  #集群名字
---
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
---
spring:
  profiles: pro1
server:
  port: 8085
---
spring:
  profiles: pro2
server:
  port: 8086
---
spring:
  profiles: dev1
server:
  port: 8081
---
spring:
  profiles: dev2
server:
  port: 8082

